package gong_cheng_bu

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	XiangMuBiaoRouter
	XiangMuShiGongBiaoRouter
	FenBaoShangBiaoRouter
	FenBaoShangYuXiangMuGuanLianBiaoRouter
	HeTongWenJianBiaoRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
