package gong_cheng_bu

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	XiangMuBiaoRouter
	XiangMuShiGongBiaoRouter
	FenBaoShangBiaoRouter
	FenBaoShangYuXiangMuGuanLianBiaoRouter
	HeTongWenJianBiaoRouter
	GongYingShangBiaoRouter
	XiangMuZhuCaiBiaoRouter
	CaiGouJiHuaBiaoRouter
	CaiGouJiHuaMingXiBiaoRouter
	ChuRuKuDanJuBiaoRouter
	ChuRuKuMingXiBiaoRouter
	SheBeiZuLinBiaoRouter
	SheBeiMingXiBiaoRouter
	ShiGongJinDuBiaoRouter
	WenJianZiLiaoJieDianBiaoRouter
	WenJianZiLiaoBiaoRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
