package hr

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	YuanGongHuaMingCeApi
	MeiRiKaoQinApi
	KaoQinTongJiApi
	QingJiaGuanLiApi
	HuiYuanGuanLiApi
	GongSiZhangHaoMiMaApi
	GongZhangDengJiApi
	ZhengShuBiaoApi
	ZhengShuJieChuJiLuBiaoApi
	XiaoXiTongZhiApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
