package cai_wu_bu

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	NeiBuBaoXiaoBiaoApi
	WaiBuFeiYongQingKuanBiaoApi
	YingShouKuanBiaoApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
