package hr


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	YuanGongHuaMingCeService
	MeiRiKaoQinService
	KaoQinTongJiService
	QingJiaGuanLiService
	HuiYuanGuanLiService
	GongSiZhangHaoMiMaService
	GongZhangDengJiService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

