package gong_cheng_bu

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	XiangMuBiaoApi
	XiangMuShiGongBiaoApi
	FenBaoShangBiaoApi
	FenBaoShangYuXiangMuGuanLianBiaoApi
	HeTongWenJianBiaoApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
