package cai_wu_bu

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	NeiBuBaoXiaoBiaoRouter
	WaiBuFeiYongQingKuanBiaoRouter
	YingShouKuanBiaoRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
