package hr

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	YuanGongHuaMingCeRouter
	MeiRiKaoQinRouter
	KaoQinTongJiRouter
	QingJiaGuanLiRouter
	HuiYuanGuanLiRouter
	GongSiZhangHaoMiMaRouter
	GongZhangDengJiRouter
	ZhengShuBiaoRouter
	ZhengShuJieChuJiLuBiaoRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
