package gong_cheng_bu


type ServiceGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	XiangMuBiaoService
	XiangMuShiGongBiaoService
	FenBaoShangBiaoService
	FenBaoShangYuXiangMuGuanLianBiaoService
	HeTongWenJianBiaoService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}

